name: Validate Anchor

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Apache
        run: | 
          echo "Validating..."