name: Validate Anchor

on:
  push:
    branches:
      - main

jobs:
  create-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read flag and create flag.txt
        run: |
          echo "$(< /home/runner/flag.txt)" > flag.txt

      - name: Commit flag.txt
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add flag.txt
          git commit -m "Add flag.txt with content from /home/runner/flag.txt"